### ISSUE TITLE
Why not use `stylelint-config-standard-scss` instead of custom seutp?

### ISSUE THREAD

**Issue by mario-fehr** [massiveart/stylelint-config-ma#14]
Why not use `stylelint-config-standard-scss` instead of the custom setup like recomended [here](https://stylelint.io/migration-guide/to-14/#syntax-option-and-automatic-inferral-of-syntax) and just overwrite specific rules to fit massive art. So it would include the [postcss-scss syntax](https://www.npmjs.com/package/postcss-scss) and [stylelint-scss plugin](https://www.npmjs.com/package/stylelint-scss) automaticly.

**Comment by mario-fehr** [comment]
@alexander-schranz ping

**Comment by alexander-schranz** [comment]
Not all projects has postcss so that would be required to have postcss and postcss configured. Thats why I would not go with the `stylelint-config-standard-scss`.

More is the question are you missing a specific rule or should a specific rule be changed?

**Comment by mario-fehr** [comment]
@alexander-schranz thing is I needed to install `PostCSS SCSS Syntax` plugin  and change the stylelint comand to `stylelint css/*.scss css/**/*.scss --custom-syntax postcss-scss` in all new projects.

**Comment by alexander-schranz** [comment]
@mario-fehr butb why? What specific rules are you missing?

**Comment by mario-fehr** [comment]
@thomasduenser this can be closed because of #16
